# Generated by Django 4.1.1 on 2022-10-04 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_project_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='site',
            field=models.URLField(blank=True),
        ),
    ]
