# Generated by Django 4.1.1 on 2022-10-06 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_project_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('Side Project', 'Side project'), ('Internship Project', 'Internship project'), ('Work Project', 'Work project')], default='Side project', max_length=20),
        ),
    ]
