# Generated by Django 4.1.1 on 2022-10-14 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_alter_softskill_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='end_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='start_date',
            field=models.DateField(default=None, null=True),
        ),
    ]
