# Generated by Django 4.1.1 on 2022-10-25 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_rename_hobbies_profile_hobbies_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='./static/images/profile-pictures/pp-1.jpg', upload_to='portfolio/static/images/profile-pictures/'),
        ),
    ]
